name: news
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  #------------------------PACKAGES-------------------#
dependencies:
  flutter:
    sdk: flutter

  #Utilitiy Packages

  dio: ^5.8.0+1
  dartz: ^0.10.1
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1

  #Assets
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  #State Management

  flutter_bloc: ^9.0.0
  #----------------------PACKAGES END-----------------#
  bloc: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #------------------------LOCAL ASSETS-------------------#
 # assets:
    #- assets/images/bag/


  #------------------------LOCAL FONTS-------------------#
 # fonts:
    #- family: Playball
     # fonts:
     #   - asset: assets/fonts/Playball-Regular.ttf

   # - family: Poppins
     # fonts:
       #- asset: assets/fonts/poppins/Poppins-Medium.ttf
       # - asset: assets/fonts/poppins/Poppins-Regular.ttf

